server:
  port: 8888
spring:
  profiles:
    active: jdbc
  datasource:
    driver-class: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=CONFIGSERVER;
    username: mnk413
    password: 413
  cloud:
    config:
      server:
        jdbc:
          sql: select keyName,value from properties where application=? and profile=? and label=?
